### ISSUE TITLE
SuperTuxKart irc moved!

### ISSUE THREAD

**Issue by Benau** [wlxmhls/cnTowerMeal#1]
Hi

Seem no email for you then let me tell you:

I saw you connectes today asking why only 12 users in (old) freenode stk irc channel, because we moved to libera.chat #supertuxkart

See you there

**Comment by wlxmhls** [comment]
okay, thanks. see you.
----- 原始邮件 -----
发件人：Benau ***@***.***>
收件人：wlxmhls/cnTowerMeal ***@***.***>
抄送人：Subscribed ***@***.***>
主题：[wlxmhls/cnTowerMeal] SuperTuxKart irc moved! (#1)
日期：2021年06月16日 18点52分


Hi
Seem no email for you then let me tell you:
I saw you connectes today asking why only 12 users in (old) freenode stk irc channel, because we moved to libera.chat #supertuxkart
See you there

&mdash;
